os: Visual Studio 2017

environment:
  image: Visual Studio 2017

build_script:
  - cmd: msbuild /t:restore;build;pack .\sometest\sometest.csproj

nuget:
  project_feed: true

artifacts:
  - path: 'bin\**\*.nupkg'
