os: Visual Studio 2017

environment:
  image: Visual Studio 2017

before_build:
  - cmd: choco install gitversion.portable
  - cmd: gitversion /output buildserver

build_script:
  - cmd: msbuild /t:restore;build;pack .\sometest.sln

nuget:
  project_feed: true

artifacts:
  - path: '**\*.nupkg'

on_finish:
  - cmd: dotnet run --project .\tools\BuildAgent.csproj
