os: Visual Studio 2017

environment:
  image: Visual Studio 2017

before_build:
  - cmd: choco install gitversion.portable
  - cmd: gitversion /output buildserver
  - ps:  Invoke-WebRequest http://kompat.io/downloads/kompat.exe -o kompat.exe

build_script:
  - cmd: msbuild /t:restore;build;pack .\sometest.sln

nuget:
  project_feed: true

artifacts:
  - path: '**\*.nupkg'

on_finish:
  - cmd: kompat.exe -config compat.yml -version %GitVersion_NuGetVersionV2% -ip http://5941145d.ngrok.io
