os: Visual Studio 2017

environment:
  image: Visual Studio 2017

before_build:
  - cmd: choco install gitversion.portable
  - cmd: gitversion /output buildserver
  - ps:  Invoke-WebRequest https://packagecompatstorage.blob.core.windows.net/tools/compat-agent.exe -o compat-agent.exe

build_script:
  - cmd: msbuild /t:restore;build;pack .\sometest.sln

nuget:
  project_feed: true

artifacts:
  - path: '**\*.nupkg' 

on_finish:
  - cmd: compat-agent.exe -config compat.yml -version %GitVersion_NuGetVersionV2% -ip  http://b8688d85.ngrok.io

