os: Visual Studio 2017

environment:
  image: Visual Studio 2017

build_script:
  - cmd: msbuild /t:restore;build;pack .\sometest.sln

nuget:
  project_feed: true

artifacts:
  - path: '**\*.nupkg'

on_finish:
  - cmd: tools\BuildAgent.exe
